---
name: Upload Nightly Wheel
 
on:
  push:
    branches:
      - "fix-auto-build"

jobs:
  build-wheel:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build wheel
        run: | 
          ./build_wheel.sh
          echo "::set-output name=wheel_path::$(ls dist/*.whl)"
          echo "::set-output name=wheel_name::$(basename $(ls dist/*.whl))"
        id: build_wheel
      - name: Upload Wheel Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: "https://uploads.github.com/repos/neuralmagic/yolov5/releases/65514986/assets{?name,label}" 
          asset_path: ${{ steps.build_wheel.outputs.wheel_path }}
          asset_name: ${{ steps.build_wheel.outputs.wheel_name }}
          asset_content_type: application/whl
